### ISSUE TITLE
Review and Refactor Matlab Code

### ISSUE THREAD

**Issue by yujanshrestha** [innolitics/freesurfer#2]
The overarching goal of this ticket is to gauge how easy it will be to work with the Matlab code and identify risky areas that could affect the assessment deliverable. A good way to do this is to read through and refactor the code for readability and testability. 

- Identify good points to break up a large matlab script into smaller scripts in a pipeline. Each step in the pipeline will read and write files. The Python port will mirror this structure so we can easily ensure numerical equivalence at each step.
- Refactor the samseg Matlab code into smaller functions to improve readability.

Ideally the above should be done in order. First identify good splice points, then refactor.

**Comment by yujanshrestha** [comment]
Let's not sink too much time into getting a fully functioning development environment until we meeting with Nick and the team. Lets focus our efforts for this week on getting more familiar with the code + samseg paper so we can be as confident as possible for our assessment deliverable.

**Comment by orwonthe** [comment]
These matlab files need conversion to python:
	

- kvlColorCodeProbabilityImages.m
- 	kvlMergeAlphas.m
- 	kvlReadCompressionLookupTable.m
- 	run_samseg.m
- 	samseg_registerAtlas.m
- 	samsegment.m

These matlab runners need equivalent python or c++ runners:

- 	kvlClear.h
- 	kvlCreateImage.h
- 	kvlCreateTransform.h
- 	kvlEvaluateMeshPosition.h
- 	kvlGetAlphasInMeshNodes.h
- 	kvlGetCostAndGradientCalculator.h

		'MutualInformation' 'Affine'
		'AtlasMeshToIntensityImage' 'Sliding'*


	

- kvlGetOptimizer.h

		 'L-BFGS'

- 	kvlGetTransformMatrix.h
- 	kvlRasterizeAtlasMesh.h
- 	kvlReadMesh.h ???
- 	kvlReadMeshCollection.h
- 	kvlScaleMesh.h
- 	kvlSetAlphasInMeshNodes.h
- 	kvlSetMeshNodePositions.h
- 	kvlSmoothImageBuffer.h
- 	kvlSmoothMesh.h
- 	kvlStepOptimizer.h
- 	kvlWriteImage.h

These kvl functions may need wrapping to be called from python:
	

- kvlAtlasMeshAlphaDrawer.h
- 	kvlAtlasMeshDeformationOptimizer.h
- 	kvlAtlasMeshDeformationLBFGSOptimizer.h
- 	kvlAtlasMeshCollection.h
- 	kvlAtlasMeshSmoother.h
- 	kvlAtlasMeshMultiAlphaDrawer.h
- 	kvlAtlasMeshPositionCostAndGradientCalculator.h
- 	kvlCroppedImageReader.h
- 	kvlImageConverter.h
- 	kvlMutualInformationCostAndGradientCalculator.h

These ITK inclusions may need wrapping:

- 	#include "itkCastImageFilter.h"
- 	#include "itkDefaultStaticMeshTraits.h"
- 	#include "itkDefaultDynamicMeshTraits.h"
- 	#include "itkMesh.h"
- 	#include "itkImage.h"
- 	#include "itkImageFileWriter.h"
- 	#include "itkImageRegionIterator.h"
- 	#include <itkMath.h>
- 	#include "itkMGHImageIO.h"
- 	#include "itkVector.h"

These VNL inclusions may need wrapping:

- 	#include "vnl/vnl_matrix_fixed.h"
- 	#include "vnl/vnl_inverse.h"
- 	#include "vnl/vnl_det.h"
